spring:
  application:
    name: hospital

  datasource:
    url: "jdbc:mysql://localhost:3306/easy-doc?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      jdbc:
        time_zone: UTC
  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: a87da0d17f6af3
    password: b0926bb023fc01
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.thymeleaf: DEBUG
    org.attoparser: DEBUG
    #org.thymeleaf.TemplateEngine.CONFIG: TRACE
    rg.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
